Milestone 5: Friendships v1
mke2111/ror-social-scaffold pull request #2
Opened 2020-12-14 20:34 UTC by edxco

In this milestone we implemented the following features:

- Friendship mutual associations.
- Send Friend request feature in views.
- Confirm the Friend request feature in views.
- Add custom methods to the User model.
- Rspec tests for models and features using Capybara.

2020-12-14 21:53 UTC, bertil291utn requested changes
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish as the actual page, you required to do these changes, listed below:

### General requirements
Edit and change the branch name, the name should be one that defines this work
### Specific requirements 
* [ ] There is a button to invite the user to friendship on the users list page and on single-user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
  - Add a button next to see profile button
![image](https://user-images.githubusercontent.com/24902525/102139329-b5d3bb00-3e2b-11eb-8058-34b6c36042b7.png)
  -  Requirements ask about a button not a link , change it 
![image](https://user-images.githubusercontent.com/24902525/102139458-ddc31e80-3e2b-11eb-98ed-5acc40e69502.png)

 -  Fix the next requirement and please be sure the other requirements are working
* [ ] User can invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [ ] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [ ] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [ ] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

![image](https://user-images.githubusercontent.com/24902525/102139599-0ba86300-3e2c-11eb-8179-4a6accc5a981.png)


### OPTIONAL
- Add the current user name in the navbar element, to know which user is current logged in 

### Summary
- Fix the options the send a friendship request
- As is not working the friendship request function, the other requirements I can't review, please work on it to review on the next one 
-  Don't forget to work with inline comments below this comment box.

***

Guys work on the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-12-14 21:53 UTC, bertil291utn commented on app/models/user.rb
>    # Include default devise modules. Others available are:
Disabled linters
- Remove statement that disables linters, because it's not good practice to disable them

2020-12-15 02:55 UTC, acushlakoncept requested changes
Looking at the previous review, I can't help notice the significant improvement on your codebase, that's very commendable, well done! 👏 

I noticed you missed out on the part you were asked to "Remove statement that disables linters, because it's not good practice to disable them"
Inside your `User Model` I notice you still have `# rubocop:disable all` please kindly remove it. Rubocop is there to help us write better codes by enforcing some of its rules, if something is wrong find a way to refactor your code, you will be surprised how better you could become by aligning yourself to some of its guidelines.

- [ ] I am sorry, the previous TSE forgot to mention this, but it's absolutely necessary that you maintain some of these good coding practices in order to be better as we progress along with our software development career.
* There should be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it. 
Affected files:
> `layouts/application.html.erb`
> `users/_received_request.html.erb`
> `users/_user.html.erb`
> `users/index.html.erb`
> `users/show.html.erb`

**The Resources below can come in handy**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright
#### Kindly remove all logics from view related files and use helpers.

Great job so far guys !!! 👍 

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-12-15 16:29 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

There is still some logic left in your views after the previous review. I have marked them. 
  - [ ] Please go over and move them to helpers.

That's it!

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-12-15 16:29 UTC, tirthajyoti-ghosh commented on app/views/layouts/application.html.erb
> +      <% end %>
Please move this logic to helpers.

2020-12-15 16:29 UTC, tirthajyoti-ghosh commented on app/views/users/_received_request.html.erb
> +  <% end %>
Please move this logic to helpers.

2020-12-15 16:29 UTC, tirthajyoti-ghosh commented on app/views/users/_user.html.erb
> +  <% end %>
Please move this logic to helpers.

2020-12-15 16:29 UTC, tirthajyoti-ghosh commented on app/views/users/index.html.erb
> +      <% end %>
Please move this logic to helpers.

2020-12-15 16:29 UTC, tirthajyoti-ghosh commented on app/views/users/index.html.erb
> +      <% end %>
Please move this logic to helpers.

2020-12-15 16:29 UTC, tirthajyoti-ghosh commented on app/views/users/show.html.erb
> +  <% end %>
Please move this logic to helpers.

2020-12-15 20:29 UTC, blackpintz requested changes
# Status: Changes Required 

## Hello team 😃,

**Great job on your project 💪. However, the changes requested by the previous TSE haven't been implemented yet. The only change made was in the `app/views/user/index.html.erb` file. Please work on the rest as well.**

### Happy coding 🥂.

**PS: You can reach me on slack (Rose Wanjohi).**

2020-12-15 21:20 UTC, blackpintz requested changes
# Status: Changes Required 

**You are almost there team 💪. Here is the list of files that still have logic in them.**

- `app/views/layouts/application.html.erb`.
- `app/views/users/_user.html.erb `.

I also noticed your RSpec tests are not passing anymore.

![rspec](https://user-images.githubusercontent.com/38922385/102274568-287c8d80-3f35-11eb-9e4d-82139ac62263.png)

2020-12-16 02:04 UTC, acushlakoncept approved these changes
# Status: PROJECT APPROVED  🎉 🚀

I see both of you have made lots of changes to meet all requirements, I am sure you will be proud of yourselves at the end of this project. 
#### Congratulations you've both done well on this milestone 👏 👏 👏 

I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next milestone.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-12-16 02:20 UTC, merged